version: '3'

networks:
  web:

services:
  java-fcgi:
    build:
      context: .
    networks:
      - web

  frontend:
    build:
      context: ./front
    networks:
      - web  
  
  nginx:
    image: nginx
    ports:
      - "8001:80"
    depends_on:
      - java-fcgi
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - web 
