version: '3'

networks:
  web:

services:
  java-fcgi:
    build:
      context: .
    networks:
      - web
  
  nginx:
    build:
      context: ./front
    ports:
      - "8080:80"
    depends_on:
      - java-fcgi
    networks:
      - web 
