networks:
  lab3:

services:
  postgresDB:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab3db
    networks:
      - lab3

  mysqlDB:
    image: mysql:latest
    ports:
      - "8306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab3db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql-files/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lab3


  wildfly:
    build: .
    ports:
      - "8083:8080"
    depends_on:

      - postgresDB
      - mysqlDB
    networks:
      - lab3